server:
  port: 8082


spring:
    datasource:
        name: prod
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://localhost:3306/vehicle?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
          username: root
          password: admin@123
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

          thymeleaf:
             cache: false

    activemq:
      #ActiveMQ通讯地址
      broker-url: tcp://localhost:61627
      #用户名
      user: admin
      #密码
      password: admin
      #是否启用内存模式（就是不安装MQ，项目启动时同时启动一个MQ实例）
      in-memory: false
      packages:
        #信任所有的包
        trust-all: true
      pool:
        #是否替换默认的连接池，使用ActiveMQ的连接池需引入的依赖
        enabled: false

    mvc:
      static-path-pattern: /**

    servlet:
      multipart:
        enabled: true # 是否支持批量上传
        max-file-size: 1024MB # 上传文件最大为 10M
        max-request-size: 1024MB # 上传请求最大为 10M
        file-size-threshold: 0 # 文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中（默认值0 一般情况下不用特意修改）
        location:   # 上传文件的临时目录 (一般不用特意修改)
        resolve-lazily: false # 判断是否要延迟解析文件（相当于懒加载，一般情况下不用特意修改）

    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D://video/

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.sys.entity



#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check



logging:
  level:
    com.example.sys.mapper : debug